#!/usr/bin/env bash

clojure -A:test -n babashka.pods.jvm-test
#clojure -A:test:kaocha --focus babashka.pods.jvm-test

clojure -A:sci:test -n babashka.pods.sci-test
#clojure -A:sci:test:kaocha --focus babashka.pods.sci-test
